### ISSUE TITLE
Reproducibility problem in binary classification in DDI.

### ISSUE THREAD

**Issue by sunwoongc** [wanwenzeng/deepdrug#4]
Hi, I'm trying to run your code and replicate the result of the paper.

Since the paper said, it achieved a 0.916-0.955 F1 score as the highest in the 'Result' section, also the figure showed that it achieved about 0.95 F1 score with 1-Ratio(balanced) case.

However, with running the code with your repo, it is only possible to achieve about a 0.71 F1 score, I found that in the code you use a balanced DrugBank dataset.

Am I doing something wrong? Is there any way to replicate the result properly?

**Comment by QijinYin** [comment]
Hi, do you use the dataset attached with the repo? The dataset attached is a demo dataset which is tiny and not complete. 
The complete dataset can be download from https://tdcommons.ai/multi_pred_tasks/ddi/. 
Hope it helps.

**Comment by sunwoongc** [comment]
Thanks for the quick reply, then can I replicate the result by downloading the dataset from the link you mentioned and preprocessing it with your Data processing module?

**Comment by QijinYin** [comment]
yeah
