### ISSUE TITLE
can't find the file:PAIRPred_feature_dict.npz

### ISSUE THREAD

**Issue by siyuzhixin** [wanwenzeng/deepdrug#5]
Hi, thanks for the dataset and code. The readme intrthe dataset. The readme introduced the proteins features are constructed by [PAIRPred]software,but I can't find the file:PAIRPred_feature_dict.npz anywhere. I would appreciate it if you could provide the file : PAIRPred_feature_dict.npz.
Thank you very much!

**Comment by QijinYin** [comment]
Hi, we had released processed datasets on [figshare](https://figshare.com/articles/dataset/Datasets_fo_DeepDrug/20306445). PAIRPred_feature_dict.npz is not necessary.  Hope it helps.

**Comment by siyuzhixin** [comment]
Thanks for your help ,but when run this file ,it have a error: RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.so I want to regenerate this data.pt file.

**Comment by siyuzhixin** [comment]
Thanks for your help ,but when I run this project ,it have a error: RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.so I want to regenerate this data.pt file.So I would appreciate it if you could provide the file : PAIRPred_feature_dict.npz. Thank you very much!
By the way, are you Chinese?

**Comment by siyuzhixin** [comment]
> Hi, we had released processed datasets on [figshare](https://figshare.com/articles/dataset/Datasets_fo_DeepDrug/20306445). PAIRPred_feature_dict.npz is not necessary. Hope it helps.

Thanks for your help ,but when I run this project ,it have a error: RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.so I want to regenerate this data.pt file.So I would appreciate it if you could provide the file : PAIRPred_feature_dict.npz. Thank you very much!
By the way, are you Chinese?

**Comment by siyuzhixin** [comment]
Or could you provide the data format with the PAIRPred_feature_dict.npz?

**Comment by QijinYin** [comment]
Hi, are you using PyG with a version > v2.0.0?  To be compatible with heterogeneous graphs, PyG has modified many underlying interfaces in v2.0.0. I cannot guarantee that the **model** (and **dataset**) classes will work successfully under PyG v2.0.0+. For convenience, please use PyG < v2.0.0 (v1.7.1 is recommended and tested). Thanks.
